### ISSUE TITLE
Where put database info ?

### ISSUE THREAD

**Issue by shortymc** [emily61268/FavMusic-Web-App#1]
Hi,
thanks you very much for your work and open source sharing
i'm trying to install it but i don't know where i can put the info of my mysql database.
Also i wanna know if the mssql file is working with mysql ?

 Best regards

**Comment by emily61268** [comment]
> Hi,
> thanks you very much for your work and open source sharing
> i'm trying to install it but i don't know where i can put the info of my mysql database.
> Also i wanna know if the mssql file is working with mysql ?
> 
> Best regards

Hello, thank you for your interest in this project. To use your own database, you should modify the "config.php" file which is in the "includes" folder. Please replace 

`$con = mysqli_connect("localhost", "root", "", "favmusic");`

with
`$con = mysqli_connect("__________(hostname)", "__________(username)", "_________(password)", "_________(database)");`

And add the following code below the if statement in the file and fill in the information in which I marked underlined.

```
        //Get Heroku ClearDB connection information
	$active_group = 'default';
	$query_builder = TRUE;

	$db['default'] = array(
	    'dsn'    => '',
	    'hostname' => '___________',
	    'username' => '___________',
	    'password' => '____________',
	    'database' => '_____________',
	    'dbdriver' => 'mysqli',
	    'dbprefix' => '',
	    'pconnect' => FALSE,
	    'db_debug' => (ENVIRONMENT !== 'production'),
	    'cache_on' => FALSE,
	    'cachedir' => '',
	    'char_set' => 'utf8',
	    'dbcollat' => 'utf8_general_ci',
	    'swap_pre' => '',
	    'encrypt' => FALSE,
	    'compress' => FALSE,
	    'stricton' => FALSE,
	    'failover' => array(),
	    'save_queries' => TRUE
	);
```

**Comment by shortymc** [comment]
Thanks for you fast response and help
It's working, but files folders for music and images is missing.
Can you help me ?
It's a really nice work.
I hope use it in production/

 Have a nice day/night

 Best regards

**Comment by emily61268** [comment]
> Thanks for you fast response and help
> It's working, but files folders for music and images is missing.
> Can you help me ?
> It's a really nice work.
> I hope use it in production/
> 
> Have a nice day/night
> 
> Best regards

Hi, because of copyright concerns, unfortunately I cannot provide music and images.
